# Generated by Django 5.0.14 on 2026-02-20 16:21

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cross_road', models.CharField(help_text="Nearest intersection, e.g. 'Canal St & Bourbon St'", max_length=255)),
                ('street_address', models.CharField(blank=True, help_text='Specific address if known', max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Geographic coordinates (longitude, latitude)', srid=4326)),
                ('facial_recognition', models.BooleanField(default=False, help_text='Does this camera have facial recognition capability?')),
                ('associated_shop', models.CharField(blank=True, help_text='Business name if this is a private camera', max_length=255)),
                ('status', models.CharField(choices=[('vetted', 'Vetted'), ('pending', 'Pending Review'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about this camera')),
                ('reported_by', models.CharField(blank=True, help_text='Email or name of person who reported this camera', max_length=255)),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('vetted_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, help_text='Photo of the camera', null=True, upload_to='camera_images/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vetted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vetted_cameras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Camera',
                'verbose_name_plural': 'Cameras',
                'ordering': ['-reported_at'],
            },
        ),
    ]
