# Generated by Django 5.0.14 on 2026-02-21 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='image_2',
            field=models.ImageField(blank=True, help_text='Photo of the camera and its surroundings', null=True, upload_to='camera_images/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='camera',
            name='image_3',
            field=models.ImageField(blank=True, help_text='Photo of a Project Nola sign (if present)', null=True, upload_to='camera_images/%Y/%m/'),
        ),
    ]
