# Generated by Django 5.0.14 on 2026-02-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_camera_image_2_camera_image_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='cross_road',
            field=models.CharField(blank=True, help_text="Nearest intersection, e.g. 'Canal St & Bourbon St'", max_length=255),
        ),
    ]
