# Generated by Django 5.0.14 on 2026-03-08 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0005_announcement_siteinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteInfo',
            new_name='AboutSection',
        ),
        migrations.AlterModelOptions(
            name='aboutsection',
            options={'verbose_name': 'About Section', 'verbose_name_plural': 'About Section'},
        ),
    ]
