# Generated by Django 5.0.14 on 2026-03-15 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0006_rename_siteinfo_to_aboutsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='osm_id',
            field=models.BigIntegerField(blank=True, help_text='OpenStreetMap node ID (for deduplication and future OSM contribution)', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='camera_type',
            field=models.CharField(choices=[('project_nola', 'Project NOLA'), ('nopd', 'NOPD'), ('private', 'Private'), ('traffic', 'Traffic'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20),
        ),
    ]
