# Generated by Django 5.0.14 on 2026-03-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0007_camera_osm_id_alter_camera_camera_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='direction',
            field=models.CharField(blank=True, help_text='Camera pointing direction in degrees (0-359) or cardinal', max_length=20),
        ),
        migrations.AddField(
            model_name='camera',
            name='manufacturer',
            field=models.CharField(blank=True, help_text="Camera manufacturer (e.g. 'Neology, Inc.')", max_length=255),
        ),
        migrations.AlterField(
            model_name='camera',
            name='camera_type',
            field=models.CharField(choices=[('project_nola', 'Project NOLA'), ('nopd', 'NOPD'), ('private', 'Private'), ('traffic', 'Traffic'), ('alpr', 'ALPR'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20),
        ),
    ]
