# Generated by Django 5.0.14 on 2026-04-28 19:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0008_camera_direction_camera_manufacturer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='camera_images/%Y/%m/')),
                ('photo_type', models.CharField(choices=[('surrounding', 'Surrounding'), ('close_up', 'Close Up'), ('project_nola_sign', 'Project NOLA Sign')], default='close_up', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('proposed_by', models.CharField(blank=True, max_length=255)),
                ('proposed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cameras.camera')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Camera Image',
                'verbose_name_plural': 'Camera Images',
                'ordering': ['photo_type', '-proposed_at'],
            },
        ),
    ]
