# Generated by Django 5.0.14 on 2026-04-28 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0010_migrate_camera_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='image',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='image_3',
        ),
    ]
