# Generated by Django 5.0.14 on 2026-04-29 11:11

import cameras.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0011_drop_camera_image_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameraimage',
            name='image',
            field=models.ImageField(upload_to=cameras.models._camera_image_upload_to),
        ),
    ]
